// 問題データ定義ファイル
// カテゴリ(category)、レベル(level: 'choice' | 'fill' | 'write')ごとに問題を追加していく。
// choice: options(4択) + answerIndex
// fill: code中の ___ を埋める。answer(文字列) or options(プルダウン用)
// write: 白紙記述。judge: 'exact'(完全一致) or 'partial'(キーワード部分一致)。keywords: partial判定用の配列

const QUESTIONS = [
  // =========================================
  // カテゴリ: let/const とスコープ
  // =========================================
  {
    id: "scope-1",
    category: "let/const とスコープ",
    group: "es6",
    level: "choice",
    question: "次のコードを実行するとどうなるか?\n\nconst x = 1;\nx = 2;\nconsole.log(x);",
    options: ["2 が出力される", "TypeError が発生する", "undefined が出力される", "1 が出力される"],
    answerIndex: 1,
    reason: "const で宣言した変数は再代入できないため、TypeError: Assignment to constant variable. が発生する。",
    example: "// let なら再代入してもエラーにならない\nlet y = 1;\ny = 2;\nconsole.log(y); // 2",
  },
  {
    id: "scope-2",
    category: "let/const とスコープ",
    group: "es6",
    level: "choice",
    question: "var と let の最も大きな違いは何か?",
    options: ["var はブロックスコープ、let は関数スコープ", "var は関数スコープ、let はブロックスコープ", "var と let はどちらも同じスコープを持つ", "let は再代入できない"],
    answerIndex: 1,
    reason: "var は関数スコープ(またはグローバルスコープ)を持ち、let/const は {} で囲まれたブロックスコープを持つ。",
    example: "if (true) {\n  var a = 1;\n  let b = 2;\n}\nconsole.log(a); // 1(varはブロックの外でも見える)\nconsole.log(b); // ReferenceError(letはブロックの外から見えない)",
  },
  {
    id: "scope-3",
    category: "let/const とスコープ",
    group: "es6",
    level: "choice",
    question: "次のコードの出力は?\n\nfor (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}",
    options: ["0 1 2", "3 3 3", "0 0 0", "エラーになる"],
    answerIndex: 1,
    reason: "var は関数スコープなので、ループ終了後の i の値(3)が全てのコールバックで共有されて出力される。let なら各ループごとに新しいスコープが作られ 0 1 2 になる。",
    example: "// let に変えると期待通りの結果になる\nfor (let i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}\n// => 0 1 2",
  },
  {
    id: "scope-4",
    category: "let/const とスコープ",
    group: "es6",
    level: "choice",
    question: "const で宣言したオブジェクトについて正しいものはどれか?",
    options: ["プロパティの変更もできない", "再代入はできないが、プロパティの変更はできる", "再代入はできるが、プロパティの変更はできない", "そもそも const でオブジェクトは宣言できない"],
    answerIndex: 1,
    reason: "const は変数の再代入を禁止するだけで、オブジェクトや配列の中身(プロパティ)の変更は可能。",
    example: 'const user = { name: "太郎" };\nuser.name = "次郎"; // OK(プロパティの変更)\nuser = {};           // TypeError(変数自体の再代入は禁止)',
  },
  {
    id: "scope-5",
    category: "let/const とスコープ",
    group: "es6",
    level: "choice",
    question: "次のコードはどうなるか?\n\nconsole.log(a);\nlet a = 10;",
    options: ["undefined が出力される", "10 が出力される", "ReferenceError が発生する(TDZ)", "何も起きない"],
    answerIndex: 2,
    reason: "let/const は宣言前にアクセスすると一時的死角(Temporal Dead Zone)により ReferenceError になる。var は undefined になる点と対比して覚える。",
    example: "// var の場合はエラーにならず undefined になる\nconsole.log(b); // undefined\nvar b = 10;",
  },
  {
    id: "scope-6",
    category: "let/const とスコープ",
    group: "es6",
    level: "fill",
    question: "再代入は不可だが、配列の中身は変更したい場合に使うキーワードを埋めよ。\n\n___ arr = [1, 2, 3];\narr.push(4);",
    answer: "const",
    reason: "const は再代入を禁止するが、配列やオブジェクトの中身の変更は許可される。",
    example: "const arr = [1, 2, 3];\narr.push(4);   // OK(中身の変更)\narr = [9, 9];  // TypeError(配列自体の再代入は禁止)",
  },
  {
    id: "scope-7",
    category: "let/const とスコープ",
    group: "es6",
    level: "write",
    question: "ブロックスコープを持ち、後で値を再代入する可能性がある変数 count を 0 で初期化する宣言文を書け。",
    judge: "partial",
    keywords: ["let", "count", "0"],
    sampleAnswer: "let count = 0;",
    reason: "再代入の可能性がある場合は let を使う。const は再代入不可なので不適切。",
    example: "let count = 0;\ncount = count + 1; // OK\n\nconst total = 0;\ntotal = total + 1; // TypeError(constは再代入できない)",
  },

  // =========================================
  // カテゴリ: アロー関数
  // =========================================
  {
    id: "arrow-1",
    category: "アロー関数",
    group: "es6",
    level: "choice",
    question: "アロー関数と通常の関数(function)の大きな違いはどれか?",
    options: ["アロー関数は自分自身の this を持たない", "アロー関数は必ず引数を1つしか取れない", "アロー関数は非同期処理に使えない", "アロー関数は再帰呼び出しができない"],
    answerIndex: 0,
    reason: "アロー関数は独自の this を持たず、定義された時点の外側スコープの this を引き継ぐ(レキシカルスコープ)。",
    example: "// 通常の関数は呼び出し方によって this が変わる\nfunction Normal() {\n  this.value = 1;\n  setTimeout(function () {\n    console.log(this.value); // undefined(thisがずれる)\n  }, 0);\n}",
  },
  {
    id: "arrow-2",
    category: "アロー関数",
    group: "es6",
    level: "choice",
    question: "次のうち、引数が1つの場合に丸括弧を省略できる正しいアロー関数はどれか?",
    options: ["x => x * 2", "(x) => { x * 2 }", "x -> x * 2", "function x => x * 2"],
    answerIndex: 0,
    reason: "引数が1つのときは括弧を省略できる。x => x * 2 は x を受け取り x*2 を返す。",
    example: '// 引数が0個や2個以上のときは括弧を省略できない\nconst greet = () => "hi";\nconst add = (a, b) => a + b;',
  },
  {
    id: "arrow-3",
    category: "アロー関数",
    group: "es6",
    level: "choice",
    question: "オブジェクトリテラルを暗黙的に返すアロー関数として正しい書き方はどれか?",
    options: ["() => { name: 'A' }", "() => ({ name: 'A' })", "() => [name: 'A']", "() -> { name: 'A' }"],
    answerIndex: 1,
    reason: "{} は関数本体のブロックと解釈されるため、オブジェクトを返す場合は () で囲む必要がある。",
    example: '// () で囲まないと {} が関数本体とみなされ、オブジェクトは返らない\nconst getObj = () => { name: "A" }; // 文法エラー、または undefined を返す\nconst getObjOk = () => ({ name: "A" }); // OK',
  },
  {
    id: "arrow-4",
    category: "アロー関数",
    group: "es6",
    level: "choice",
    question: "次のコードの出力は?\n\nconst obj = {\n  value: 10,\n  getValue: () => this.value\n};\nconsole.log(obj.getValue());",
    options: ["10", "undefined", "TypeError", "0"],
    answerIndex: 1,
    reason: "アロー関数は自分の this を持たないため、obj ではなく外側(この場合グローバル)の this が使われ、value は undefined になる。",
    example: "// 通常の関数(メソッド)にすれば this は obj を指す\nconst obj2 = {\n  value: 10,\n  getValue: function () { return this.value; }\n};\nconsole.log(obj2.getValue()); // 10",
  },
  {
    id: "arrow-5",
    category: "アロー関数",
    group: "es6",
    level: "fill",
    question: "2つの数値を足し合わせて返すアロー関数を、波括弧・return を省略した形式で埋めよ。\n\nconst add = (a, b) ___ a + b;",
    answer: "=>",
    reason: "波括弧を省略した場合、=> の右側の式が自動的に返り値になる(暗黙のreturn)。",
    example: "// 波括弧を使う場合は return を書かないと undefined になる\nconst addBlock = (a, b) => {\n  return a + b; // return を書き忘れると undefined\n};",
  },
  {
    id: "arrow-6",
    category: "アロー関数",
    group: "es6",
    level: "write",
    question: "配列 nums の各要素を2倍にした新しい配列を返す、map とアロー関数を使った1行のコードを書け(nums は既に定義されているものとする)。",
    judge: "partial",
    keywords: ["nums.map", "=>"],
    sampleAnswer: "nums.map(n => n * 2);",
    reason: "map にアロー関数を渡すことで簡潔に変換処理を書ける。",
    example: "// 通常の関数を渡しても同じ結果になるが、アロー関数の方が簡潔\nconst doubled = nums.map(function (n) {\n  return n * 2;\n});",
  },

  // =========================================
  // カテゴリ: 分割代入(配列・オブジェクト)
  // =========================================
  {
    id: "destr-1",
    category: "分割代入(配列・オブジェクト)",
    group: "es6",
    level: "choice",
    question: "次のコードの結果は?\n\nconst [a, b] = [1, 2, 3];\nconsole.log(a, b);",
    options: ["1 2", "1 2 3", "undefined undefined", "エラーになる"],
    answerIndex: 0,
    reason: "配列の分割代入では、左辺の変数の数だけ先頭から順に値が取り出される。余った要素は無視される。",
    example: "// 変数の数が要素数より多いと、足りない分は undefined になる\nconst [x, y, z, w] = [1, 2, 3];\nconsole.log(w); // undefined",
  },
  {
    id: "destr-2",
    category: "分割代入(配列・オブジェクト)",
    group: "es6",
    level: "choice",
    question: "オブジェクトの分割代入で、プロパティ名を別名にして取り出す正しい書き方はどれか?",
    options: ["const { name: userName } = obj;", "const { name -> userName } = obj;", "const { userName: name } = obj;", "const [name as userName] = obj;"],
    answerIndex: 0,
    reason: "{ 元のプロパティ名: 新しい変数名 } の形で別名をつけて取り出せる。",
    example: '// 別名をつけずそのまま取り出す場合はプロパティ名と同じ変数名になる\nconst obj = { name: "太郎" };\nconst { name } = obj;\nconsole.log(name); // "太郎"',
  },
  {
    id: "destr-3",
    category: "分割代入(配列・オブジェクト)",
    group: "es6",
    level: "choice",
    question: "次のコードの出力は?\n\nconst { a = 10 } = {};\nconsole.log(a);",
    options: ["undefined", "10", "エラーになる", "null"],
    answerIndex: 1,
    reason: "分割代入ではデフォルト値を指定でき、対象のプロパティが存在しない(またはundefined)場合はデフォルト値が使われる。",
    example: "// プロパティが存在する場合はデフォルト値は使われない\nconst { a = 10 } = { a: 5 };\nconsole.log(a); // 5",
  },
  {
    id: "destr-4",
    category: "分割代入(配列・オブジェクト)",
    group: "es6",
    level: "choice",
    question: "配列の分割代入で、先頭要素をスキップして2番目の要素だけ取得する正しい書き方はどれか?",
    options: ["const [, second] = arr;", "const [skip, second] = arr;", "const [_, second] = arr; // _ は特別な構文", "const [second] = arr[1];"],
    answerIndex: 0,
    reason: "分割代入ではカンマだけを置くことで要素をスキップできる。",
    example: "// 複数の要素を続けてスキップすることもできる\nconst [, , third] = [1, 2, 3];\nconsole.log(third); // 3",
  },
  {
    id: "destr-5",
    category: "分割代入(配列・オブジェクト)",
    group: "es6",
    level: "fill",
    question: "オブジェクト user から name と age を分割代入で取り出すコードを埋めよ。\n\nconst ___ = user;",
    answer: "{ name, age }",
    reason: "オブジェクトの分割代入は { プロパティ名 } の形で書く。",
    example: '// 一部のプロパティだけ取り出すことも可能\nconst user = { name: "太郎", age: 20, job: "engineer" };\nconst { name } = user; // ageとjobは無視される',
  },
  {
    id: "destr-6",
    category: "分割代入(配列・オブジェクト)",
    group: "es6",
    level: "write",
    question: "配列 [1, 2, 3, 4, 5] の先頭要素を first、残りを rest として分割代入するコードを書け(レスト構文を使うこと)。",
    judge: "partial",
    keywords: ["first", "...rest", "="],
    sampleAnswer: "const [first, ...rest] = [1, 2, 3, 4, 5];",
    reason: "レスト構文(...)を使うと残りの要素を配列としてまとめて取得できる。",
    example: '// オブジェクトの分割代入でもレスト構文が使える\nconst { name, ...others } = { name: "太郎", age: 20, job: "engineer" };\nconsole.log(others); // { age: 20, job: "engineer" }',
  },

  // =========================================
  // カテゴリ: スプレッド構文
  // =========================================
  {
    id: "spread-1",
    category: "スプレッド構文",
    group: "es6",
    level: "choice",
    question: "次のコードの結果は?\n\nconst a = [1, 2];\nconst b = [...a, 3];\nconsole.log(b);",
    options: ["[1, 2, 3]", "[[1, 2], 3]", "[1, 2]", "エラーになる"],
    answerIndex: 0,
    reason: "スプレッド構文は配列を展開して新しい配列に組み込む。b は [1, 2, 3] になる。",
    example: "// 先頭に展開することもできる\nconst a = [1, 2];\nconst c = [0, ...a]; // [0, 1, 2]",
  },
  {
    id: "spread-2",
    category: "スプレッド構文",
    group: "es6",
    level: "choice",
    question: "2つのオブジェクトをマージする正しい方法はどれか?",
    options: ["const merged = obj1 + obj2;", "const merged = { ...obj1, ...obj2 };", "const merged = obj1.merge(obj2);", "const merged = Object.add(obj1, obj2);"],
    answerIndex: 1,
    reason: "スプレッド構文をオブジェクトリテラル内で使うと、プロパティを展開してマージできる。後ろに書いたものが優先される。",
    example: "// Object.assign() でも同じことができる(スプレッド構文の方が簡潔)\nconst merged2 = Object.assign({}, obj1, obj2);",
  },
  {
    id: "spread-3",
    category: "スプレッド構文",
    group: "es6",
    level: "choice",
    question: "次のコードの出力は?\n\nconst obj1 = { a: 1, b: 2 };\nconst obj2 = { b: 3, c: 4 };\nconsole.log({ ...obj1, ...obj2 });",
    options: ["{ a: 1, b: 2, c: 4 }", "{ a: 1, b: 3, c: 4 }", "{ a: 1, b: 2 }", "エラーになる"],
    answerIndex: 1,
    reason: "後から展開されたオブジェクトのプロパティが同名の場合上書きされる。b は obj2 の 3 になる。",
    example: "// 順番を入れ替えるとどちらが優先されるかも変わる\nconsole.log({ ...obj2, ...obj1 }); // { b: 2, c: 4, a: 1 }(今度はobj1のbが優先)",
  },
  {
    id: "spread-4",
    category: "スプレッド構文",
    group: "es6",
    level: "choice",
    question: "関数呼び出し時に配列を個別の引数として渡す用途で使うのはどれか?",
    options: ["レスト構文", "スプレッド構文", "分割代入", "テンプレートリテラル"],
    answerIndex: 1,
    reason: "func(...args) のようにスプレッド構文を使うと、配列の要素を個別の引数として展開して渡せる。",
    example: "// 配列の最大値を求める際によく使われる\nconst nums = [5, 2, 8, 1];\nconsole.log(Math.max(...nums)); // 8",
  },
  {
    id: "spread-5",
    category: "スプレッド構文",
    group: "es6",
    level: "fill",
    question: "配列 arr の浅いコピーを作るコードを埋めよ。\n\nconst copy = [___arr];",
    answer: "...",
    reason: "スプレッド構文を使うと配列の浅いコピーを簡単に作成できる。",
    example: "// コピー後は元の配列と別物になるため、片方を変更しても影響しない\nconst copy2 = [...arr];\ncopy2.push(4);\nconsole.log(arr); // 元のarrには4は追加されない",
  },
  {
    id: "spread-6",
    category: "スプレッド構文",
    group: "es6",
    level: "write",
    question: "オブジェクト user のコピーを作り、age プロパティだけ 30 に上書きした新しいオブジェクトを作るコードを書け。",
    judge: "partial",
    keywords: ["...user", "age", "30"],
    sampleAnswer: "const updated = { ...user, age: 30 };",
    reason: "スプレッド構文で既存プロパティを展開したあとに同名プロパティを書くと上書きされる。",
    example: '// 複数のプロパティをまとめて上書きすることもできる\nconst updated2 = { ...user, age: 30, job: "designer" };',
  },

  // =========================================
  // カテゴリ: 配列操作(map / filter / reduce)
  // =========================================
  {
    id: "array-1",
    category: "配列操作(map / filter / reduce)",
    group: "es6",
    level: "choice",
    question: "map メソッドの説明として正しいものはどれか?",
    options: ["条件に合う要素だけを抽出した新しい配列を返す", "各要素に処理を適用した新しい配列を返す", "配列を1つの値に集約する", "元の配列を直接変更する"],
    answerIndex: 1,
    reason: "map は各要素にコールバック関数を適用し、その結果からなる新しい配列を返す(元の配列は変更しない)。",
    example: "// forEachは新しい配列を返さない点がmapと異なる\nconst nums = [1, 2, 3];\nconst result = nums.forEach(n => n * 2);\nconsole.log(result); // undefined",
  },
  {
    id: "array-2",
    category: "配列操作(map / filter / reduce)",
    group: "es6",
    level: "choice",
    question: "次のコードの出力は?\n\nconst nums = [1, 2, 3, 4, 5];\nconsole.log(nums.filter(n => n % 2 === 0));",
    options: ["[1, 3, 5]", "[2, 4]", "[1, 2, 3, 4, 5]", "true"],
    answerIndex: 1,
    reason: "filter はコールバックが true を返す要素だけを抽出した新しい配列を返す。偶数は 2 と 4。",
    example: "// 条件に一致する要素が1つもない場合は空配列になる\nconsole.log([1, 3, 5].filter(n => n % 2 === 0)); // []",
  },
  {
    id: "array-3",
    category: "配列操作(map / filter / reduce)",
    group: "es6",
    level: "choice",
    question: "配列の合計値を求めるのに最も適したメソッドはどれか?",
    options: ["map", "filter", "reduce", "forEach"],
    answerIndex: 2,
    reason: "reduce は配列を1つの値に集約する処理に適しており、合計値の計算によく使われる。",
    example: "// 最大値を求めるなど、合計以外の集約にも使える\nconst max = [3, 7, 2].reduce((acc, cur) => (cur > acc ? cur : acc));\nconsole.log(max); // 7",
  },
  {
    id: "array-4",
    category: "配列操作(map / filter / reduce)",
    group: "es6",
    level: "choice",
    question: "次のコードの出力は?\n\nconst total = [1, 2, 3].reduce((acc, cur) => acc + cur, 0);\nconsole.log(total);",
    options: ["6", "0", "[1, 2, 3]", "undefined"],
    answerIndex: 0,
    reason: "reduce は初期値0から始めて acc に cur を順に足し込み、最終的に 6 になる。",
    example: "// 初期値を省略すると配列の先頭要素が初期値として使われる\nconst total2 = [1, 2, 3].reduce((acc, cur) => acc + cur);\nconsole.log(total2); // 6(この場合は同じ結果)",
  },
  {
    id: "array-5",
    category: "配列操作(map / filter / reduce)",
    group: "es6",
    level: "fill",
    question: "配列 nums の中から10より大きい要素だけを抽出するコードを埋めよ。\n\nconst result = nums.___(n => n > 10);",
    answer: "filter",
    reason: "条件に合う要素の抽出には filter を使う。",
    example: "// mapと組み合わせて、抽出してから変換することもできる\nconst result2 = nums.filter(n => n > 10).map(n => n * 2);",
  },
  {
    id: "array-6",
    category: "配列操作(map / filter / reduce)",
    group: "es6",
    level: "fill",
    question: "配列 names の各要素を大文字に変換した新しい配列を作るコードを埋めよ。\n\nconst upper = names.___(name => name.toUpperCase());",
    answer: "map",
    reason: "各要素を変換した新しい配列を作るには map を使う。",
    example: '// 文字列を数値に変換するなど、型を変えるmapもよく使われる\nconst strNums = ["1", "2", "3"];\nconst intNums = strNums.map(Number); // [1, 2, 3]',
  },
  {
    id: "array-7",
    category: "配列操作(map / filter / reduce)",
    group: "es6",
    level: "write",
    question: "配列 prices([100, 200, 300])から、200以上の値だけを合計した数値を求めるコードを filter と reduce を使って書け。",
    judge: "partial",
    keywords: ["filter", "reduce", ">=", "200"],
    sampleAnswer: "const total = prices.filter(p => p >= 200).reduce((acc, cur) => acc + cur, 0);",
    reason: "filter で条件抽出した後、reduce で合計する組み合わせはよく使われるパターン。",
    example: "// 該当件数を数えたい場合はfilterの結果のlengthを使う\nconst count = prices.filter(p => p >= 200).length;",
  },

  // =========================================
  // カテゴリ: async/await
  // =========================================
  {
    id: "async-1",
    category: "async/await",
    group: "es6",
    level: "choice",
    question: "async 関数の戻り値について正しいものはどれか?",
    options: ["常に undefined を返す", "常に Promise を返す", "常に配列を返す", "呼び出し元によって型が変わる"],
    answerIndex: 1,
    reason: "async 関数は常に Promise を返す。関数内で return した値は Promise.resolve() でラップされる。",
    example: "// 戻り値をそのまま使おうとすると Promise オブジェクトが表示される\nasync function getNum() { return 1; }\nconsole.log(getNum()); // Promise { 1 }\ngetNum().then(n => console.log(n)); // 1",
  },
  {
    id: "async-2",
    category: "async/await",
    group: "es6",
    level: "choice",
    question: "await はどこで使えるか?",
    options: ["どこでも自由に使える", "async 関数の内部でのみ使える(またはトップレベル)", "for ループの中でのみ使える", "Promise を返さない関数の中でのみ使える"],
    answerIndex: 1,
    reason: "await は async 関数の内部、もしくはES modulesのトップレベルでのみ使用できる。",
    example: "// asyncの付いていない通常関数の中でawaitを使うと文法エラーになる\nfunction bad() {\n  const data = await fetch(url); // SyntaxError\n}",
  },
  {
    id: "async-3",
    category: "async/await",
    group: "es6",
    level: "choice",
    question: "async/await で例外(エラー)を処理する正しい方法はどれか?",
    options: ["if文でエラーかどうかを判定する", "try/catch で囲む", "async関数はエラーを発生させない", ".then() を必ず併用する"],
    answerIndex: 1,
    reason: "await でエラーが発生した場合(Promiseがreject)、try/catch でキャッチするのが標準的な方法。",
    example: '// Promiseの.catch()を使う書き方も等価だが、async/awaitではtry/catchが一般的\nasync function run() {\n  try {\n    await mightFail();\n  } catch (e) {\n    console.log("失敗:", e);\n  }\n}',
  },
  {
    id: "async-4",
    category: "async/await",
    group: "es6",
    level: "choice",
    question: "次のコードの動作として正しいものはどれか?\n\nasync function getData() {\n  const res = await fetch(url);\n  const data = await res.json();\n  return data;\n}",
    options: ["fetch の完了を待たずに res.json() が実行される", "fetch の完了を待ってから res.json() が実行される", "getData は Promise を返さない", "エラーが必ず発生する"],
    answerIndex: 1,
    reason: "await を使うことで、fetch の Promise が解決するまで処理を一時停止し、順番に実行される。",
    example: "// awaitを付け忘れるとPromiseのまま次の処理に進んでしまう\nasync function bad() {\n  const res = fetch(url); // awaitがない\n  const data = res.json(); // TypeError(resはまだPromise)\n}",
  },
  {
    id: "async-5",
    category: "async/await",
    group: "es6",
    level: "fill",
    question: "非同期関数であることを示すキーワードを埋めよ。\n\n___ function getData() {\n  const data = await fetch(url);\n}",
    answer: "async",
    reason: "関数内で await を使うには、関数の宣言に async キーワードを付ける必要がある。",
    example: "// アロー関数にもasyncを付けられる\nconst getData2 = async () => {\n  const data = await fetch(url);\n};",
  },
  {
    id: "async-6",
    category: "async/await",
    group: "es6",
    level: "write",
    question: "async関数 loadUser 内で、fetch(url) の結果をエラーハンドリングしつつ取得し、コンソールにログ出力するコードを書け(try/catch を使うこと)。",
    judge: "partial",
    keywords: ["async", "try", "catch", "await", "fetch"],
    sampleAnswer: "async function loadUser() {\n  try {\n    const res = await fetch(url);\n    const data = await res.json();\n    console.log(data);\n  } catch (error) {\n    console.log(error);\n  }\n}",
    reason: "async関数の中でawaitを使い、エラーはtry/catchで捕捉するのが基本パターン。",
    example: '// finallyを使うと成功・失敗に関わらず必ず実行される処理を書ける\nasync function loadUser2() {\n  try {\n    await fetch(url);\n  } catch (error) {\n    console.log(error);\n  } finally {\n    console.log("読み込み処理が終了しました");\n  }\n}',
  },

  // =========================================
  // カテゴリ: fetch API
  // =========================================
  {
    id: "fetch-1",
    category: "fetch API",
    group: "es6",
    level: "choice",
    question: "fetch() の戻り値は何か?",
    options: ["JSONオブジェクト", "文字列", "Promise", "配列"],
    answerIndex: 2,
    reason: "fetch() は Promise を返す。レスポンスの本文を取得するには .json() などをさらに呼ぶ必要がある。",
    example: "// .then()でPromiseの結果を受け取ることもできる\nfetch(url).then(res => console.log(res)); // Response {...}",
  },
  {
    id: "fetch-2",
    category: "fetch API",
    group: "es6",
    level: "choice",
    question: "fetch でレスポンスをJSONとしてパースする正しい方法はどれか?",
    options: ["const data = fetch(url).json();", "const data = await fetch(url).json();", "const res = await fetch(url); const data = await res.json();", "const data = JSON.stringify(fetch(url));"],
    answerIndex: 2,
    reason: "fetch のレスポンス自体もPromiseで、さらに res.json() もPromiseを返すため、両方 await する必要がある。",
    example: "// .then()を連結して書くこともできる\nfetch(url)\n  .then(res => res.json())\n  .then(data => console.log(data));",
  },
  {
    id: "fetch-3",
    category: "fetch API",
    group: "es6",
    level: "choice",
    question: "fetch でPOSTリクエストを送る際、body に含めるデータをJSON文字列に変換するために使うメソッドはどれか?",
    options: ["JSON.parse()", "JSON.stringify()", "String()", "toJSON()"],
    answerIndex: 1,
    reason: "リクエストボディに送るオブジェクトは JSON.stringify() で文字列に変換する必要がある。",
    example: '// 受け取ったJSON文字列をオブジェクトに戻す場合はJSON.parse()を使う\nconst str = JSON.stringify({ name: "test" }); // \'{"name":"test"}\'\nconst obj = JSON.parse(str); // { name: "test" }',
  },
  {
    id: "fetch-4",
    category: "fetch API",
    group: "es6",
    level: "choice",
    question: "fetch が404エラーを返した場合の挙動として正しいものはどれか?",
    options: ["fetch の Promise が自動的に reject される", "fetch の Promise は resolve され、res.ok が false になる", "例外がthrowされる", "fetchはHTTPステータスコードを扱わない"],
    answerIndex: 1,
    reason: "fetch はネットワークエラー以外(404や500など)ではrejectされず、res.ok(false)やres.statusで判定する必要がある。",
    example: '// res.okやres.statusで自分でエラー処理を行う\nconst res = await fetch(url);\nif (!res.ok) {\n  console.log("エラー:", res.status); // 例: 404\n}',
  },
  {
    id: "fetch-5",
    category: "fetch API",
    group: "es6",
    level: "fill",
    question: "GETで取得したレスポンスをJSONに変換するコードを埋めよ。\n\nconst res = await fetch(url);\nconst data = await res.___();",
    answer: "json",
    reason: "res.json() でレスポンスボディをJSONとしてパースしたPromiseを取得できる。",
    example: "// レスポンスがJSONでなくテキストの場合はres.text()を使う\nconst res2 = await fetch(url);\nconst text = await res2.text();",
  },
  {
    id: "fetch-6",
    category: "fetch API",
    group: "es6",
    level: "write",
    question: "fetch を使って url に POST リクエストを送り、JSON形式のbody({ name: 'test' })を送信するコードを書け(method と headers、body を指定すること)。",
    judge: "partial",
    keywords: ["fetch", "method", "POST", "headers", "JSON.stringify"],
    sampleAnswer: "fetch(url, {\n  method: 'POST',\n  headers: { 'Content-Type': 'application/json' },\n  body: JSON.stringify({ name: 'test' })\n});",
    reason: "POSTリクエストでは method、Content-Typeを含むheaders、JSON.stringifyしたbodyを指定するのが基本形。",
    example: '// DELETEやPUTもmethodを変えるだけで同じ形で書ける\nfetch(url, { method: "DELETE" });',
  },

  // =========================================
  // 基礎編 カテゴリ: 変数とデータ型
  // =========================================
  {
    id: "basic-datatype-1",
    category: "変数とデータ型",
    group: "basic",
    level: "choice",
    question: "次のうち、JavaScriptのプリミティブ型に含まれないものはどれか?",
    options: ["string", "boolean", "配列(Array)", "undefined"],
    answerIndex: 2,
    reason: "配列はオブジェクト型であり、プリミティブ型(string, number, boolean, undefined, null, symbol, bigint)には含まれない。",
    example: '// typeofで確認すると配列もオブジェクトも "object" になる\nconsole.log(typeof [1, 2, 3]); // "object"\nconsole.log(typeof { a: 1 }); // "object"',
  },
  {
    id: "basic-datatype-2",
    category: "変数とデータ型",
    group: "basic",
    level: "choice",
    question: "次のコードの出力は?\n\nconsole.log(typeof null);",
    options: ['"null"', '"undefined"', '"object"', "エラーになる"],
    answerIndex: 2,
    reason: 'typeof null は歴史的な仕様上のバグにより "object" を返す(JavaScriptの有名な仕様)。',
    example: 'console.log(typeof null);      // "object"\nconsole.log(typeof undefined); // "undefined"\nconsole.log(null === undefined); // false(値も型も違う)',
  },
  {
    id: "basic-datatype-3",
    category: "変数とデータ型",
    group: "basic",
    level: "choice",
    question: "undefined と null の違いとして正しいものはどれか?",
    options: ["undefined は「値が未代入」、null は「意図的に空」を表す", "undefined と null は完全に同じ意味である", "null は数値型の一種である", "undefined は文字列型の一種である"],
    answerIndex: 0,
    reason: "undefined は変数が宣言されただけで値が代入されていない状態、null は開発者が意図的に「値がない」ことを示すために代入する値。",
    example: "let a;\nconsole.log(a); // undefined(何も代入していない)\n\nlet b = null;\nconsole.log(b); // null(意図的に空を代入)",
  },
  {
    id: "basic-datatype-4",
    category: "変数とデータ型",
    group: "basic",
    level: "choice",
    question: '次のコードの出力は?\n\nconsole.log(typeof "123");',
    options: ['"number"', '"string"', '"boolean"', '"undefined"'],
    answerIndex: 1,
    reason: 'クォートで囲まれた "123" は数値ではなく文字列(string)として扱われる。',
    example: '// クォートを外せば数値として扱われる\nconsole.log(typeof 123); // "number"\nconsole.log("123" === 123); // false(型が違う)',
  },
  {
    id: "basic-datatype-5",
    category: "変数とデータ型",
    group: "basic",
    level: "choice",
    question: "オブジェクトを作成する正しい書き方はどれか?",
    options: ["const obj = (name: 'A');", "const obj = [name: 'A'];", "const obj = { name: 'A' };", "const obj = <name: 'A'>;"],
    answerIndex: 2,
    reason: "オブジェクトリテラルは波括弧 {} を使い、プロパティ名: 値 の形式で記述する。",
    example: "// 配列は角括弧[]を使う点でオブジェクトと区別される\nconst arr = [1, 2, 3];      // 配列\nconst obj = { a: 1, b: 2 }; // オブジェクト",
  },
  {
    id: "basic-datatype-6",
    category: "変数とデータ型",
    group: "basic",
    level: "choice",
    question: "次のコードの出力は?\n\nconsole.log(typeof true);",
    options: ['"boolean"', '"true"', '"number"', '"string"'],
    answerIndex: 0,
    reason: 'true / false は真偽値(boolean)型であり、typeof は "boolean" を返す。',
    example: '// 比較演算の結果もboolean型になる\nconsole.log(typeof (1 < 2)); // "boolean"',
  },

  // =========================================
  // 基礎編 カテゴリ: 演算子
  // =========================================
  {
    id: "basic-operator-1",
    category: "演算子",
    group: "basic",
    level: "choice",
    question: '次のコードの出力は?\n\nconsole.log(1 == "1");',
    options: ["true", "false", "エラーになる", "undefined"],
    answerIndex: 0,
    reason: '== は型変換を行ってから比較するため、数値の1と文字列の"1"は等しいと判定される。',
    example: '// === を使うと型変換されずfalseになる\nconsole.log(1 === "1"); // false',
  },
  {
    id: "basic-operator-2",
    category: "演算子",
    group: "basic",
    level: "choice",
    question: '次のコードの出力は?\n\nconsole.log(1 === "1");',
    options: ["true", "false", "エラーになる", "undefined"],
    answerIndex: 1,
    reason: "=== は型変換を行わない厳密等価演算子のため、数値と文字列は型が異なり false になる。",
    example: "// 値と型が両方一致する場合のみtrueになる\nconsole.log(1 === 1);   // true\nconsole.log(1 === 1.0); // true(同じnumber型で同じ値)",
  },
  {
    id: "basic-operator-3",
    category: "演算子",
    group: "basic",
    level: "choice",
    question: "次のコードの出力は?\n\nconsole.log(true && false);",
    options: ["true", "false", "undefined", "エラーになる"],
    answerIndex: 1,
    reason: "&& は両方が true のときのみ true を返す論理積演算子。片方が false なので false になる。",
    example: "// 両方trueのときだけtrueになる\nconsole.log(true && true);  // true\nconsole.log(false && false); // false",
  },
  {
    id: "basic-operator-4",
    category: "演算子",
    group: "basic",
    level: "choice",
    question: '次のコードの出力は?\n\nconsole.log(false || "デフォルト値");',
    options: ["false", '"デフォルト値"', "undefined", "true"],
    answerIndex: 1,
    reason: '|| は左辺がfalsyな場合に右辺の値を返す論理和演算子。false はfalsyなので右辺の"デフォルト値"が返る。',
    example: '// 左辺がtruthyな場合は左辺の値がそのまま返る\nconsole.log("入力値" || "デフォルト値"); // "入力値"',
  },
  {
    id: "basic-operator-5",
    category: "演算子",
    group: "basic",
    level: "choice",
    question: "!true の結果はどれか?",
    options: ["true", "false", "undefined", "エラーになる"],
    answerIndex: 1,
    reason: "! は論理否定演算子で、真偽値を反転させる。!true は false になる。",
    example: '// !!(2回否定)でtruthy/falsyな値をbooleanに変換できる\nconsole.log(!!"文字列"); // true\nconsole.log(!!"");      // false',
  },
  {
    id: "basic-operator-6",
    category: "演算子",
    group: "basic",
    level: "choice",
    question: "三項演算子の正しい構文はどれか?",
    options: ["条件 ? 真の場合の値 : 偽の場合の値", "条件 : 真の場合の値 ? 偽の場合の値", "if (条件) ? 真の場合の値 : 偽の場合の値", "条件 => 真の場合の値 : 偽の場合の値"],
    answerIndex: 0,
    reason: "三項演算子は「条件 ? 真の場合の値 : 偽の場合の値」という構文で、if/elseを1行で表現できる。",
    example: '// if/elseで書くと同じ処理はこうなる\nlet result;\nif (isValid) {\n  result = "OK";\n} else {\n  result = "NG";\n}',
  },
  {
    id: "basic-operator-7",
    category: "演算子",
    group: "basic",
    level: "choice",
    question: '次のコードの出力は?\n\nconst age = 20;\nconsole.log(age >= 18 ? "成人" : "未成年");',
    options: ['"成人"', '"未成年"', "true", "20"],
    answerIndex: 0,
    reason: 'age(20)は18以上なので条件式は true となり、三項演算子は "成人" を返す。',
    example: '// ageを17に変えると条件式がfalseになり結果が変わる\nconst age2 = 17;\nconsole.log(age2 >= 18 ? "成人" : "未成年"); // "未成年"',
  },

  // =========================================
  // 基礎編 カテゴリ: 条件分岐
  // =========================================
  {
    id: "basic-if-1",
    category: "条件分岐",
    group: "basic",
    level: "choice",
    question: '次のコードの出力は?\n\nconst score = 75;\nif (score >= 80) {\n  console.log("A");\n} else if (score >= 60) {\n  console.log("B");\n} else {\n  console.log("C");\n}',
    options: ['"A"', '"B"', '"C"', "何も出力されない"],
    answerIndex: 1,
    reason: 'scoreは75で、最初の条件(80以上)は満たさないが2番目の条件(60以上)を満たすため "B" が出力される。',
    example: '// scoreを50に変えるとどの条件にも一致せずelse節が実行される\nconst score2 = 50;\nif (score2 >= 80) {\n  console.log("A");\n} else if (score2 >= 60) {\n  console.log("B");\n} else {\n  console.log("C"); // ここが実行される\n}',
  },
  {
    id: "basic-if-2",
    category: "条件分岐",
    group: "basic",
    level: "choice",
    question: "switch文で、どの case にも一致しなかった場合に実行される節はどれか?",
    options: ["else", "default", "otherwise", "catch"],
    answerIndex: 1,
    reason: "switch文では、どのcaseにも一致しない場合の処理を default 節に記述する。",
    example: '// defaultはどこに書いても良いが、慣習的に最後に置く\nswitch (value) {\n  case 1:\n    console.log("one");\n    break;\n  default:\n    console.log("other");\n}',
  },
  {
    id: "basic-if-3",
    category: "条件分岐",
    group: "basic",
    level: "choice",
    question: '次のコードの出力は?\n\nconst fruit = "apple";\nswitch (fruit) {\n  case "banana":\n    console.log("バナナ");\n    break;\n  case "apple":\n    console.log("りんご");\n    break;\n  default:\n    console.log("不明");\n}',
    options: ['"バナナ"', '"りんご"', '"不明"', "何も出力されない"],
    answerIndex: 1,
    reason: 'fruitが"apple"なので case "apple" が実行され "りんご" が出力される。',
    example: '// どのcaseにも一致しない値を渡すとdefaultが実行される\nconst fruit2 = "grape";\nswitch (fruit2) {\n  case "apple":\n    console.log("りんご");\n    break;\n  default:\n    console.log("不明"); // ここが実行される\n}',
  },
  {
    id: "basic-if-4",
    category: "条件分岐",
    group: "basic",
    level: "choice",
    question: "switch文で break を書き忘れた場合に起きることはどれか?",
    options: ["エラーになる", "何も実行されなくなる", "次のcaseの処理までそのまま実行される(フォールスルー)", "switch文自体が終了する"],
    answerIndex: 2,
    reason: "breakがないと、一致したcase以降の処理がそのまま次のcaseへ続けて実行されてしまう(フォールスルー)。",
    example: '// フォールスルーをあえて利用して複数caseをまとめることもできる\nswitch (day) {\n  case "sat":\n  case "sun":\n    console.log("休日");\n    break;\n  default:\n    console.log("平日");\n}',
  },
  {
    id: "basic-if-5",
    category: "条件分岐",
    group: "basic",
    level: "choice",
    question: "if文の条件式に書ける値として正しいものはどれか?",
    options: ["boolean型の値のみ", "真偽値に変換可能な任意の値(truthy/falsyな値)", "数値型の値のみ", "文字列型の値のみ"],
    answerIndex: 1,
    reason: "if文の条件式にはboolean以外の値も書け、内部的にtruthy/falsyとして真偽値に変換されて判定される。",
    example: '// 0や空文字列、null、undefinedはfalsyとして扱われる\nif (0) { console.log("実行されない"); }\nif ("文字あり") { console.log("実行される"); }',
  },

  // =========================================
  // 基礎編 カテゴリ: ループ
  // =========================================
  {
    id: "basic-loop-1",
    category: "ループ",
    group: "basic",
    level: "choice",
    question: "次のコードの出力は?\n\nfor (let i = 0; i < 3; i++) {\n  console.log(i);\n}",
    options: ["0 1 2", "1 2 3", "0 1 2 3", "エラーになる"],
    answerIndex: 0,
    reason: "iは0から始まり、i<3の間ループするため0, 1, 2の3回出力される。",
    example: "// 条件を i <= 3 にすると0,1,2,3の4回になる\nfor (let i = 0; i <= 3; i++) {\n  console.log(i); // 0 1 2 3\n}",
  },
  {
    id: "basic-loop-2",
    category: "ループ",
    group: "basic",
    level: "choice",
    question: "次のコードの出力は?\n\nlet i = 0;\nwhile (i < 3) {\n  console.log(i);\n  i++;\n}",
    options: ["0 1 2", "無限ループになる", "0 1 2 3", "エラーになる"],
    answerIndex: 0,
    reason: "while文は条件がtrueの間繰り返される。iを毎回インクリメントしているので3回で終了し、0, 1, 2が出力される。",
    example: "// i++ を書き忘れると条件が永遠にtrueのままになり無限ループになる\nlet j = 0;\nwhile (j < 3) {\n  console.log(j); // ずっと0のまま止まらない\n}",
  },
  {
    id: "basic-loop-3",
    category: "ループ",
    group: "basic",
    level: "choice",
    question: "配列の各要素に対して処理を行うために forEach を使う場合の正しい書き方はどれか?",
    options: ["arr.forEach(item => console.log(item));", "forEach(arr, item => console.log(item));", "arr.forEach() => console.log(item);", "for (item in arr.forEach) console.log(item);"],
    answerIndex: 0,
    reason: "forEachは配列のメソッドで、各要素を引数として受け取るコールバック関数を渡して使う。",
    example: '// 第2引数でインデックスも受け取れる\n["a", "b", "c"].forEach((item, index) => {\n  console.log(index, item); // 0 "a", 1 "b", 2 "c"\n});',
  },
  {
    id: "basic-loop-4",
    category: "ループ",
    group: "basic",
    level: "choice",
    question: "for文の3つの部分(for (①; ②; ③))の正しい組み合わせはどれか?",
    options: ["① 条件式 ② 初期化式 ③ 更新式", "① 初期化式 ② 条件式 ③ 更新式", "① 更新式 ② 条件式 ③ 初期化式", "① 初期化式 ② 更新式 ③ 条件式"],
    answerIndex: 1,
    reason: "for文は for (初期化式; 条件式; 更新式) の順で構成される。",
    example: "// 更新式はi++以外にも自由に書ける(2ずつ増やす例)\nfor (let i = 0; i < 10; i += 2) {\n  console.log(i); // 0 2 4 6 8\n}",
  },
  {
    id: "basic-loop-5",
    category: "ループ",
    group: "basic",
    level: "choice",
    question: "ループを途中で完全に終了させたい場合に使う文はどれか?",
    options: ["continue", "break", "return", "stop"],
    answerIndex: 1,
    reason: "break文はループ処理を即座に終了させる。continueは現在の周回だけをスキップして次のループへ進む点で異なる。",
    example: "// continueはその回だけをスキップして次のループへ進む\nfor (let i = 0; i < 5; i++) {\n  if (i === 2) continue;\n  console.log(i); // 0 1 3 4(2だけ出力されない)\n}",
  },

  // =========================================
  // 基礎編 カテゴリ: 関数の基本
  // =========================================
  {
    id: "basic-func-1",
    category: "関数の基本",
    group: "basic",
    level: "choice",
    question: "function宣言による関数定義として正しいものはどれか?",
    options: ['function greet() { return "hello"; }', 'def greet() { return "hello"; }', 'func greet() { return "hello"; }', 'greet function() { return "hello"; }'],
    answerIndex: 0,
    reason: "function宣言は function 関数名(引数) { 処理 } という構文で記述する。",
    example: '// function宣言は定義より前の行から呼び出せる(巻き上げ)\nconsole.log(greet2()); // "hi"\nfunction greet2() { return "hi"; }',
  },
  {
    id: "basic-func-2",
    category: "関数の基本",
    group: "basic",
    level: "choice",
    question: "関数式(function expression)として正しいものはどれか?",
    options: ["function greet() {}", "const greet = function() {};", "greet = () function {};", "const greet function() {};"],
    answerIndex: 1,
    reason: "関数式は変数に無名(または名前付き)関数を代入する形式で書く。const greet = function() {}; がその例。",
    example: '// 関数式は定義より前で呼び出すとエラーになる(巻き上げされない)\nconsole.log(greet3()); // ReferenceError\nconst greet3 = function() { return "hi"; };',
  },
  {
    id: "basic-func-3",
    category: "関数の基本",
    group: "basic",
    level: "choice",
    question: "次のコードの出力は?\n\nfunction add(a, b) {\n  return a + b;\n}\nconsole.log(add(2, 3));",
    options: ["5", '"23"', "undefined", "エラーになる"],
    answerIndex: 0,
    reason: "add関数は引数aとbを受け取り、その和をreturnで返す。add(2, 3)は5を返す。",
    example: '// 引数の型によって + の意味が変わる点に注意(文字列なら連結になる)\nconsole.log(add("2", "3")); // "23"(文字列の連結)',
  },
  {
    id: "basic-func-4",
    category: "関数の基本",
    group: "basic",
    level: "choice",
    question: "return文を持たない関数を呼び出した場合の戻り値はどれか?",
    options: ["null", "0", "undefined", '空文字列""'],
    answerIndex: 2,
    reason: "return文がない関数、または値を指定せず return; とした関数は undefined を返す。",
    example: '// returnの後に書いたコードは実行されない\nfunction sample() {\n  return 1;\n  console.log("ここは実行されない");\n}',
  },
  {
    id: "basic-func-5",
    category: "関数の基本",
    group: "basic",
    level: "choice",
    question: "関数の中で宣言された変数のスコープについて正しいものはどれか?",
    options: ["関数の外からもアクセスできる", "その関数の中でのみ有効で、外からはアクセスできない", "グローバル変数として自動的に扱われる", "同名のグローバル変数を自動的に上書きする"],
    answerIndex: 1,
    reason: "関数内で宣言した変数はその関数のローカルスコープに閉じており、関数の外からは参照できない。",
    example: '// 関数の外から中の変数にアクセスしようとするとエラーになる\nfunction sample2() {\n  const local = "内部の値";\n}\nconsole.log(local); // ReferenceError',
  },
  {
    id: "basic-func-6",
    category: "関数の基本",
    group: "basic",
    level: "choice",
    question: '次のコードの出力は?\n\nfunction greet(name) {\n  console.log("こんにちは、" + name);\n}\ngreet();',
    options: ['"こんにちは、" のみ出力される', '"こんにちは、undefined" が出力される', "エラーになる", "何も出力されない"],
    answerIndex: 1,
    reason: '引数を渡さずに関数を呼び出すと、対応する仮引数の値は undefined になるため "こんにちは、undefined" と出力される。',
    example: '// デフォルト引数を設定しておくと未指定時の挙動を防げる\nfunction greet4(name = "ゲスト") {\n  console.log("こんにちは、" + name);\n}\ngreet4(); // "こんにちは、ゲスト"',
  },

  // =========================================
  // 基礎編 カテゴリ: 配列の基本操作
  // =========================================
  {
    id: "basic-array-1",
    category: "配列の基本操作",
    group: "basic",
    level: "choice",
    question: '配列の最初の要素にアクセスする正しい書き方はどれか?\n\nconst arr = ["a", "b", "c"];',
    options: ["arr.first()", "arr[0]", "arr[1]", "arr.get(0)"],
    answerIndex: 1,
    reason: "配列の要素にはインデックス(0始まり)でアクセスする。最初の要素は arr[0]。",
    example: '// 最後の要素はlengthを使って arr[arr.length - 1] で取得できる\nconst arr2 = ["a", "b", "c"];\nconsole.log(arr2[arr2.length - 1]); // "c"',
  },
  {
    id: "basic-array-2",
    category: "配列の基本操作",
    group: "basic",
    level: "choice",
    question: "配列の要素数を取得するプロパティはどれか?",
    options: ["arr.size", "arr.count", "arr.length", "arr.total"],
    answerIndex: 2,
    reason: "配列の要素数は length プロパティで取得できる。",
    example: '// lengthは文字列の文字数を取得する際にも使える\nconsole.log("hello".length); // 5',
  },
  {
    id: "basic-array-3",
    category: "配列の基本操作",
    group: "basic",
    level: "choice",
    question: "配列の末尾に要素を追加するメソッドはどれか?",
    options: ["arr.add()", "arr.append()", "arr.push()", "arr.insert()"],
    answerIndex: 2,
    reason: "push() は配列の末尾に新しい要素を追加するメソッド。",
    example: "// 先頭に追加したい場合はunshift()を使う\nconst arr3 = [2, 3];\narr3.unshift(1);\nconsole.log(arr3); // [1, 2, 3]",
  },
  {
    id: "basic-array-4",
    category: "配列の基本操作",
    group: "basic",
    level: "choice",
    question: "次のコードの出力は?\n\nconst arr = [1, 2, 3];\nconst removed = arr.pop();\nconsole.log(removed, arr);",
    options: ["3 [1, 2]", "1 [2, 3]", "3 [1, 2, 3]", "undefined [1, 2, 3]"],
    answerIndex: 0,
    reason: "pop() は配列の末尾の要素を取り除いて返す。arrは[1, 2]になり、removedには3が入る。",
    example: "// 先頭の要素を取り除きたい場合はshift()を使う\nconst arr4 = [1, 2, 3];\nconst first = arr4.shift();\nconsole.log(first, arr4); // 1 [2, 3]",
  },
  {
    id: "basic-array-5",
    category: "配列の基本操作",
    group: "basic",
    level: "choice",
    question: "次のコードの出力は?\n\nconst arr = [10, 20, 30];\nconsole.log(arr.length);",
    options: ["2", "3", "30", "undefined"],
    answerIndex: 1,
    reason: "arrには3つの要素があるため、arr.lengthは3になる。",
    example: "// lengthに直接値を代入すると配列の要素数を変更できる\nconst arr5 = [10, 20, 30];\narr5.length = 1;\nconsole.log(arr5); // [10]",
  },

  // =========================================
  // 基礎編 カテゴリ: オブジェクトの基本
  // =========================================
  {
    id: "basic-obj-1",
    category: "オブジェクトの基本",
    group: "basic",
    level: "choice",
    question: 'ドット記法でオブジェクトのプロパティにアクセスする正しい書き方はどれか?\n\nconst user = { name: "太郎" };',
    options: ["user->name", "user.name", 'user["name"()]', "user::name"],
    answerIndex: 1,
    reason: "ドット記法は オブジェクト.プロパティ名 の形式でアクセスする。",
    example: '// 存在しないプロパティにドット記法でアクセスするとundefinedになる\nconst user2 = { name: "太郎" };\nconsole.log(user2.age); // undefined',
  },
  {
    id: "basic-obj-2",
    category: "オブジェクトの基本",
    group: "basic",
    level: "choice",
    question: "ブラケット記法を使う必要があるのはどのような場合か?",
    options: ["プロパティ名が数値のみで構成される場合や、変数でプロパティ名を指定したい場合", "プロパティの値が文字列の場合", "オブジェクトが空の場合", "常にドット記法よりブラケット記法を使うべき"],
    answerIndex: 0,
    reason: 'プロパティ名に変数を使いたい場合や、プロパティ名がハイフンを含むなど識別子として不正な場合はブラケット記法 obj["key"] を使う。',
    example: '// ハイフンを含むプロパティ名はドット記法では書けない\nconst obj3 = { "first-name": "太郎" };\nconsole.log(obj3["first-name"]); // "太郎"',
  },
  {
    id: "basic-obj-3",
    category: "オブジェクトの基本",
    group: "basic",
    level: "choice",
    question: '次のコードの出力は?\n\nconst user = { name: "太郎" };\nuser.age = 20;\nconsole.log(user);',
    options: ['{ name: "太郎" }', '{ name: "太郎", age: 20 }', "エラーになる", "undefined"],
    answerIndex: 1,
    reason: "既存のオブジェクトに存在しないプロパティへ代入すると、新しいプロパティとして追加される。",
    example: '// delete演算子を使うとプロパティを削除できる\nconst user3 = { name: "太郎", age: 20 };\ndelete user3.age;\nconsole.log(user3); // { name: "太郎" }',
  },
  {
    id: "basic-obj-4",
    category: "オブジェクトの基本",
    group: "basic",
    level: "choice",
    question: '次のコードの出力は?\n\nconst user = { name: "太郎", age: 20 };\nuser.age = 25;\nconsole.log(user.age);',
    options: ["20", "25", "undefined", "エラーになる"],
    answerIndex: 1,
    reason: "既に存在するプロパティに代入すると値が上書きされる。ageは25になる。",
    example: '// ブラケット記法でも同じように上書きできる\nconst user4 = { age: 20 };\nuser4["age"] = 25;\nconsole.log(user4.age); // 25',
  },
  {
    id: "basic-obj-5",
    category: "オブジェクトの基本",
    group: "basic",
    level: "choice",
    question: '変数に格納されたキー名でプロパティにアクセスしたい場合、正しい書き方はどれか?\n\nconst user = { name: "太郎" };\nconst key = "name";',
    options: ["user.key", "user[key]", "user(key)", "user.[key]"],
    answerIndex: 1,
    reason: 'ブラケット記法では [] 内に変数を書くことができ、その変数の値がプロパティ名として評価される。user.key と書くと文字列 "key" というプロパティを探してしまう点に注意。',
    example: '// user.key と書いた場合の挙動(意図と異なる結果になる)\nconst user5 = { name: "太郎" };\nconst key2 = "name";\nconsole.log(user5.key2); // undefined("key2"というプロパティは存在しない)',
  },

  // =========================================
  // 基礎編 穴埋め式
  // =========================================
  {
    id: "basic-fill-datatype-1",
    category: "変数とデータ型",
    group: "basic",
    level: "fill",
    question: "値が「意図的に空である」ことを表すために代入する値を埋めよ。\n\nlet result = ___;",
    answer: "null",
    reason: "nullは開発者が意図的に「値がない」ことを示すために使う値。",
    example: "// 宣言だけして何も代入しない場合はundefinedになる\nlet result2;\nconsole.log(result2); // undefined",
  },
  {
    id: "basic-fill-operator-1",
    category: "演算子",
    group: "basic",
    level: "fill",
    question: "型変換を行わずに値と型の両方を比較する演算子を埋めよ。\n\nif (a ___ b) { ... }",
    answer: "===",
    reason: "=== は厳密等価演算子で、型変換を行わずに値と型の両方が一致するかを判定する。",
    example: '// !== は===の否定版で、値か型が違えばtrueになる\nconsole.log(1 !== "1"); // true',
  },
  {
    id: "basic-fill-operator-2",
    category: "演算子",
    group: "basic",
    level: "fill",
    question: '条件がtrueなら"OK"、falseなら"NG"を返す三項演算子の空欄を埋めよ。\n\nconst result = isValid ___ "OK" : "NG";',
    answer: "?",
    reason: "三項演算子は 条件 ? 真の場合の値 : 偽の場合の値 という構文。",
    example: '// 三項演算子は変数への代入だけでなく、そのままconsole.logの引数にも使える\nconsole.log(isValid ? "OK" : "NG");',
  },
  {
    id: "basic-fill-if-1",
    category: "条件分岐",
    group: "basic",
    level: "fill",
    question: '最初のif条件に一致せず、次の条件を判定したい場合に使うキーワードを埋めよ。\n\nif (a === 1) {\n  console.log("one");\n} ___ (a === 2) {\n  console.log("two");\n}',
    answer: "else if",
    reason: "else if を使うことで、最初の条件に一致しなかった場合に別の条件を続けて判定できる。",
    example: '// else if は何度でも繋げられる\nif (a === 1) {\n  console.log("one");\n} else if (a === 2) {\n  console.log("two");\n} else if (a === 3) {\n  console.log("three");\n} else {\n  console.log("other");\n}',
  },
  {
    id: "basic-fill-if-2",
    category: "条件分岐",
    group: "basic",
    level: "fill",
    question: 'switch文で、一致したcase処理後に次のcaseへ処理が続かないようにするために書く文を埋めよ。\n\ncase "a":\n  console.log("A");\n  ___;',
    answer: "break",
    reason: "break文を書くことで、そのcase処理が終わった時点でswitch文を抜けられる。",
    example: '// returnで抜ける関数の中ではbreakの代わりにreturnも使える\nfunction check(a) {\n  switch (a) {\n    case "a":\n      return "A";\n    default:\n      return "other";\n  }\n}',
  },
  {
    id: "basic-fill-loop-1",
    category: "ループ",
    group: "basic",
    level: "fill",
    question: "0から2まで3回繰り返すfor文の空欄(条件式)を埋めよ。\n\nfor (let i = 0; ___; i++) {\n  console.log(i);\n}",
    answer: "i < 3",
    reason: "i < 3 という条件により、iが0,1,2の間ループが継続する。",
    example: "// i <= 2 と書いても同じ結果になる\nfor (let i = 0; i <= 2; i++) {\n  console.log(i); // 0 1 2\n}",
  },
  {
    id: "basic-fill-loop-2",
    category: "ループ",
    group: "basic",
    level: "fill",
    question: "配列の各要素に対して処理を行うメソッド名を埋めよ。\n\narr.___(item => console.log(item));",
    answer: "forEach",
    reason: "forEachは配列の各要素に対してコールバック関数を実行するメソッド。",
    example: "// forEachの代わりにfor...ofでも同じ処理を書ける\nfor (const item of arr) {\n  console.log(item);\n}",
  },
  {
    id: "basic-fill-func-1",
    category: "関数の基本",
    group: "basic",
    level: "fill",
    question: "関数の処理結果を呼び出し元に返すために使うキーワードを埋めよ。\n\nfunction add(a, b) {\n  ___ a + b;\n}",
    answer: "return",
    reason: "return文は関数の戻り値を指定し、その時点で関数の実行を終了する。",
    example: '// 値を指定しないreturn;は途中で処理を終了するためだけに使える\nfunction checkPositive(n) {\n  if (n < 0) return;\n  console.log("正の数です");\n}',
  },
  {
    id: "basic-fill-array-1",
    category: "配列の基本操作",
    group: "basic",
    level: "fill",
    question: "配列の末尾に要素を追加するメソッド名を埋めよ。\n\nconst arr = [1, 2];\narr.___(3);",
    answer: "push",
    reason: "push()は配列の末尾に新しい要素を追加するメソッド。",
    example: "// push()は複数の値を一度に追加することもできる\nconst arr6 = [1];\narr6.push(2, 3);\nconsole.log(arr6); // [1, 2, 3]",
  },
  {
    id: "basic-fill-obj-1",
    category: "オブジェクトの基本",
    group: "basic",
    level: "fill",
    question: 'オブジェクトにageプロパティを追加するコードを埋めよ(ドット記法を使うこと)。\n\nconst user = { name: "太郎" };\nuser.___ = 20;',
    answer: "age",
    reason: "存在しないプロパティにドット記法で代入すると、新しいプロパティとして追加される。",
    example: '// ブラケット記法でも同じようにプロパティを追加できる\nconst user6 = { name: "太郎" };\nuser6["age"] = 20;\nconsole.log(user6); // { name: "太郎", age: 20 }',
  },

  // =========================================
  // 基礎編 記述式
  // =========================================
  {
    id: "basic-write-datatype-1",
    category: "変数とデータ型",
    group: "basic",
    level: "write",
    question: '文字列 "こんにちは" を値として持つ変数 message を宣言するコードを書け(再代入しない前提)。',
    judge: "partial",
    keywords: ["const", "message", "こんにちは"],
    sampleAnswer: 'const message = "こんにちは";',
    reason: "再代入しない前提なので const を使うのが適切。",
    example: '// 後から値を変える可能性があるならletを使う\nlet greeting = "こんにちは";\ngreeting = "こんばんは"; // letなら再代入できる',
  },
  {
    id: "basic-write-operator-1",
    category: "演算子",
    group: "basic",
    level: "write",
    question: "変数 score が 60 以上なら true、そうでなければ false を変数 isPassed に代入するコードを、比較演算子を使って書け。",
    judge: "partial",
    keywords: ["isPassed", "score", ">="],
    sampleAnswer: "const isPassed = score >= 60;",
    reason: ">= 演算子を使うことで比較結果の真偽値をそのまま変数に代入できる。",
    example: "// 比較演算子は<, <=, >, >=など他にも組み合わせられる\nconst isAdult = age >= 18;\nconst isChild = age < 18;",
  },
  {
    id: "basic-write-if-1",
    category: "条件分岐",
    group: "basic",
    level: "write",
    question: '変数 num が偶数なら"偶数"、奇数なら"奇数"をコンソールに出力するif文を書け(剰余演算子 % を使うこと)。',
    judge: "partial",
    keywords: ["if", "num % 2", "console.log"],
    sampleAnswer: 'if (num % 2 === 0) {\n  console.log("偶数");\n} else {\n  console.log("奇数");\n}',
    reason: "num % 2 === 0 で偶数かどうかを判定できる。",
    example: '// 三項演算子を使えばif文なしで1行に書くこともできる\nconsole.log(num % 2 === 0 ? "偶数" : "奇数");',
  },
  {
    id: "basic-write-loop-1",
    category: "ループ",
    group: "basic",
    level: "write",
    question: "1から5までの数字を順にコンソールに出力するfor文を書け。",
    judge: "partial",
    keywords: ["for", "console.log"],
    sampleAnswer: "for (let i = 1; i <= 5; i++) {\n  console.log(i);\n}",
    reason: "初期値1、条件i<=5、更新式i++のfor文で1から5まで出力できる。",
    example: "// whileでも同じ処理を書ける\nlet i = 1;\nwhile (i <= 5) {\n  console.log(i);\n  i++;\n}",
  },
  {
    id: "basic-write-func-1",
    category: "関数の基本",
    group: "basic",
    level: "write",
    question: "引数で受け取った2つの数値を掛け算した結果を返す関数 multiply を function宣言で書け。",
    judge: "partial",
    keywords: ["function", "multiply", "return"],
    sampleAnswer: "function multiply(a, b) {\n  return a * b;\n}",
    reason: "function宣言で関数を定義し、returnで計算結果を返す基本形。",
    example: "// アロー関数で同じ処理を書くとより簡潔になる\nconst multiply2 = (a, b) => a * b;",
  },
  {
    id: "basic-write-array-1",
    category: "配列の基本操作",
    group: "basic",
    level: "write",
    question: '配列 fruits の末尾に "grape" を追加し、その後配列の要素数をコンソールに出力するコードを書け。',
    judge: "partial",
    keywords: ["fruits.push", "console.log", "fruits.length"],
    sampleAnswer: 'fruits.push("grape");\nconsole.log(fruits.length);',
    reason: "push()で要素を追加し、lengthプロパティで要素数を取得できる。",
    example: '// push()は追加後の配列の要素数を戻り値として返す\nconst newLength = fruits.push("grape");\nconsole.log(newLength); // 追加後の要素数と同じ値',
  },
  {
    id: "basic-write-obj-1",
    category: "オブジェクトの基本",
    group: "basic",
    level: "write",
    question: "name と age プロパティを持つオブジェクト user を作成し、name の値をコンソールに出力するコードを書け。",
    judge: "partial",
    keywords: ["user", "name", "console.log"],
    sampleAnswer: 'const user = { name: "太郎", age: 20 };\nconsole.log(user.name);',
    reason: "オブジェクトリテラルでプロパティを定義し、ドット記法で値を取得する基本パターン。",
    example: '// ブラケット記法でも同じ値を取得できる\nconsole.log(user["name"]); // "太郎"',
  },
];
